baseURL = "https://bookofdaniel.in/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Book Of Daniel"
copyright = "2023"
theme = "diary"
